import { useState } from 'react';
import { useApp } from '../context';
import { PageHeader, Card, Button, Badge, Icon, Field, Modal } from '../components';
import { today, fmt } from '../calculations';

const recipes = [
  { name: 'Bol skyr, avoine & fruit', category: 'Petit-déjeuner', protein: 27, calories: 350, time: 3, icon: 'sun', ingredients: ['Skyr nature : 200 g', 'Flocons d’avoine : 50 g', '1 pomme ou une poignée de fruits rouges'], preparation: 'Mélange le skyr et les flocons. Ajoute les fruits coupés et un peu de cannelle.' },
  { name: 'Œufs & tartines complètes', category: 'Petit-déjeuner', protein: 24, calories: 420, time: 8, icon: 'sun', ingredients: ['3 œufs', 'Pain complet : 60 g', '1 tomate'], preparation: 'Bats les œufs et cuis-les en brouillade à la poêle. Sers avec le pain et la tomate.' },
  { name: 'Fromage blanc & banane', category: 'Petit-déjeuner', protein: 21, calories: 250, time: 2, icon: 'sun', ingredients: ['Fromage blanc nature : 250 g', '1 banane'], preparation: 'Coupe la banane et ajoute-la au fromage blanc. Sers frais.' },
  { name: 'Poulet, riz & légumes', category: 'Déjeuner / dîner', protein: 40, calories: 580, time: 20, icon: 'utensils', ingredients: ['Blanc de poulet cru : 150 g', 'Riz cru : 80 g', 'Légumes surgelés : 200 g', 'Huile : 1 cuillère à café'], preparation: 'Fais cuire le riz. Poêle le poulet émincé jusqu’à cuisson complète, puis ajoute les légumes.' },
  { name: 'Pâtes au bœuf & tomate', category: 'Déjeuner / dîner', protein: 43, calories: 560, time: 15, icon: 'utensils', ingredients: ['Steak haché 5 % cru : 150 g', 'Pâtes sèches : 80 g', 'Coulis de tomate : 100 g'], preparation: 'Cuis les pâtes. Fais cuire la viande à cœur, ajoute la tomate, puis mélange.' },
  { name: 'Omelette & pommes de terre', category: 'Déjeuner / dîner', protein: 25, calories: 510, time: 20, icon: 'utensils', ingredients: ['3 œufs', 'Pommes de terre : 250 g', 'Légumes : 150 g', 'Huile : 1 cuillère à café'], preparation: 'Cuis les pommes de terre en cubes. Ajoute les légumes, puis les œufs battus et laisse prendre.' },
  { name: 'Riz au thon express', category: 'Déjeuner / dîner', protein: 35, calories: 460, time: 12, icon: 'utensils', ingredients: ['Thon au naturel égoutté : 120 g', 'Riz cru : 80 g', 'Petits pois : 100 g'], preparation: 'Cuis le riz et les petits pois. Égoutte, ajoute le thon puis assaisonne.' },
  { name: 'Wraps poulet & yaourt', category: 'Déjeuner / dîner', protein: 40, calories: 570, time: 15, icon: 'utensils', ingredients: ['Poulet cru : 150 g', '2 tortillas de taille moyenne', 'Yaourt nature : 50 g', 'Salade et tomate'], preparation: 'Cuis le poulet à cœur. Garnis les tortillas de poulet, crudités et yaourt assaisonné, puis roule.' },
  { name: 'Pâtes au thon', category: 'Déjeuner / dîner', protein: 39, calories: 470, time: 12, icon: 'utensils', ingredients: ['Thon au naturel égoutté : 120 g', 'Pâtes sèches : 80 g', 'Coulis de tomate : 100 g'], preparation: 'Cuis les pâtes. Réchauffe doucement le thon avec la tomate puis mélange.' },
  { name: 'Lentilles & œufs', category: 'Déjeuner / dîner', protein: 30, calories: 430, time: 12, icon: 'leaf', ingredients: ['Lentilles cuites égouttées : 200 g', '2 œufs', '1 carotte râpée'], preparation: 'Fais cuire les œufs à ton goût. Réchauffe les lentilles et sers avec la carotte.' },
  { name: 'Skyr nature', category: 'Collations', protein: 20, calories: 120, time: 1, icon: 'glass', ingredients: ['Skyr nature : 200 g'], preparation: 'Sers frais. Ajoute de la cannelle si tu en as envie.' },
  { name: 'Fromage blanc', category: 'Collations', protein: 16, calories: 120, time: 1, icon: 'glass', ingredients: ['Fromage blanc nature : 200 g'], preparation: 'Sers dans un bol ; les valeurs varient selon le taux de matières grasses.' },
  { name: 'Œufs durs', category: 'Collations', protein: 13, calories: 150, time: 10, icon: 'utensils', ingredients: ['2 œufs'], preparation: 'Cuis 9 à 10 minutes dans l’eau frémissante puis refroidis avant d’écaler.' },
  { name: 'Cottage cheese & crudités', category: 'Collations', protein: 24, calories: 200, time: 3, icon: 'leaf', ingredients: ['Cottage cheese : 200 g', 'Bâtonnets de concombre'], preparation: 'Assaisonne le cottage cheese avec du poivre et accompagne de concombre.' },
  { name: 'Tartine de jambon', category: 'Collations', protein: 19, calories: 210, time: 2, icon: 'utensils', ingredients: ['Jambon blanc : 2 tranches (80 g)', 'Pain complet : 40 g'], preparation: 'Dépose le jambon sur le pain. Une option de dépannage à alterner avec les autres collations.' },
  { name: 'Shaker whey', category: 'Collations', protein: 25, calories: 120, time: 1, icon: 'glass', whey: true, ingredients: ['Ta portion habituelle de whey', 'Eau selon tes préférences'], preparation: 'Mélange dans un shaker. La quantité de protéines vient de tes paramètres et de l’étiquette.' },
];

export function Meals() {
  const { state, update, notify, toggleSupplement, navigate } = useApp();
  const [category, setCategory] = useState('Tous');
  const [selected, setSelected] = useState(null);

  function addMeal(event) {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    const date = String(form.get('date'));
    const protein = Number(form.get('protein'));
    if (!date || date > today() || !Number.isFinite(protein) || protein < 0 || protein > 600) return notify('Vérifie la date et les protéines.', 'error');
    if (selected.whey) {
      if (state.supplements[date]?.whey) return notify('Ton shaker est déjà enregistré pour cette journée.', 'error');
      toggleSupplement('whey', date);
    } else {
      update(previous => ({ ...previous, meals: [...previous.meals, { id: crypto.randomUUID(), date, name: selected.name, quantity: String(form.get('quantity')).trim() || '1 portion', protein }] }));
    }
    setSelected(null);
    notify('Ajouté à ton journal nutrition.');
  }

  return <div className="page-stack"><PageHeader eyebrow="L’INSPIRATION DU QUOTIDIEN" title="Simple. Bon. Protéiné." description="Des repas avec peu d’ingrédients et aucune complication."><Button variant="secondary" onClick={() => navigate('nutrition')}>Mon journal <Icon name="arrow-right" /></Button></PageHeader><div className="chips">{['Tous', 'Petit-déjeuner', 'Déjeuner / dîner', 'Collations'].map(item => <button key={item} className={`chip ${category === item ? 'active' : ''}`} onClick={() => setCategory(item)}>{item}</button>)}</div><p className="muted small">Valeurs approximatives par portion, à ajuster selon tes marques et quantités. Les poids crus ou égouttés sont précisés. Ajoute fruits et légumes selon tes envies.</p><div className="grid-3">{recipes.filter(recipe => category === 'Tous' || recipe.category === category).map(recipe => <Card key={recipe.name} className="recipe-card"><div className="row between"><div className="resource-icon"><Icon name={recipe.icon} size={25} /></div><Badge tone="neutral">{recipe.time} min</Badge></div><p className="muted small">{recipe.category}</p><h3>{recipe.name}</h3><div className="row"><strong className="accent">≈ {fmt(recipe.whey ? state.profile.wheyProtein : recipe.protein)} g de protéines</strong><span className="muted small">{recipe.whey ? 'Calories : voir étiquette' : `≈ ${recipe.calories} kcal`}</span></div><details><summary>Ingrédients & préparation</summary><ul className="muted small">{recipe.ingredients.map(ingredient => <li key={ingredient}>{ingredient}</li>)}</ul><p className="small">{recipe.preparation}</p></details><Button variant="secondary" onClick={() => setSelected(recipe)}><Icon name="plus" /> Ajouter au journal</Button></Card>)}</div>{selected && <Modal title={selected.name} onClose={() => setSelected(null)}><form className="page-stack" onSubmit={addMeal}><Field label="Date"><input type="date" name="date" defaultValue={today()} max={today()} required /></Field><Field label="Portion"><input name="quantity" defaultValue={selected.whey ? '1 shaker' : '1 portion'} maxLength={100} readOnly={selected.whey} required /></Field><Field label="Protéines de la portion (g)"><input type="number" name="protein" inputMode="decimal" min="0" max="600" step="0.1" defaultValue={selected.whey ? state.profile.wheyProtein : selected.protein} readOnly={selected.whey} required /></Field><p className="muted small">{selected.whey ? 'Utilise ta portion configurée dans Suppléments. Un seul shaker de suivi est ajouté par jour.' : 'Tu peux ajuster l’estimation avant d’enregistrer.'}</p><Button type="submit">Enregistrer dans mon journal</Button></form></Modal>}</div>;
}

const advice = [
  { icon: 'trending-up', title: 'D’abord les répétitions', text: 'Dans ta plage prévue, essaie de gagner une répétition avec une technique stable. Lorsque toutes tes séries atteignent le haut de la plage, teste un petit incrément de charge.', detail: 'Exemple : 3 × 8–12. Une fois 12 / 12 / 12 bien maîtrisé, augmente légèrement puis repars vers le bas de la plage.' },
  { icon: 'dumbbell', title: 'Comparer ce qui se ressemble', text: 'Garde la même machine, le même réglage et la même amplitude quand tu compares tes performances.', detail: 'Les charges de deux poulies ou machines différentes ne sont pas directement comparables.' },
  { icon: 'activity', title: 'Une technique reproductible', text: 'Contrôle la descente, stabilise ta posture et utilise une amplitude confortable. Une charge plus lourde ne vaut pas une exécution qui se dégrade.', detail: 'Sur ton Half Squat, note ta profondeur habituelle pour comparer les séances dans les mêmes conditions.' },
  { icon: 'timer', title: 'Prendre le temps de récupérer', text: 'Utilise le chrono pour garder des temps de repos comparables. Allonge le repos si tu ne retrouves pas une exécution propre.', detail: 'Le temps nécessaire dépend de l’exercice, de la charge et de la fatigue. Le chrono est réglable dans les paramètres.' },
  { icon: 'flame', title: 'Préparer la première série', text: 'Commence par quelques mouvements légers et des séries de préparation progressives sur ton premier exercice.', detail: 'Les séries d’échauffement préparent le mouvement sans chercher à te fatiguer. Le journal de séance est destiné aux séries de travail.' },
  { icon: 'moon', title: 'Laisser une place au repos', text: 'Garde des horaires de sommeil réguliers autant que possible et respecte tes journées de récupération.', detail: 'Une séance moins performante après une mauvaise nuit ne suffit pas à conclure à une régression. Regarde plusieurs semaines.' },
  { icon: 'calendar', title: 'Construire la régularité', text: 'Un programme que tu peux tenir est plus utile qu’un programme constamment abandonné. Déplace une séance quand ton agenda change.', detail: 'Le calendrier permet les déplacements ponctuels sans modifier tes jours de base.' },
  { icon: 'book', title: 'Noter le contexte', text: 'Énergie, sensations et réglages donnent du sens aux chiffres. Ajoute une phrase courte à la fin de ta séance.', detail: 'Une douleur inhabituelle mérite d’arrêter le mouvement et de demander un avis adapté si elle persiste.' },
  { icon: 'chart', title: 'Lire les bonnes tendances', text: 'Observe ensemble les charges, les répétitions, le volume et la récupération. Plus de volume n’est pas toujours mieux.', detail: 'Ne cherche pas un record à chaque séance. Une progression durable s’évalue sur plusieurs semaines.' },
];

export function Advice() {
  const { navigate } = useApp();
  return <div className="page-stack"><PageHeader eyebrow="LES BASES QUI COMPTENT" title="Progresser avec méthode." description="Des repères simples pour tes prochaines séances."><Button variant="secondary" onClick={() => navigate('arms')}>Focus bras <Icon name="arrow-right" /></Button></PageHeader><Card><div className="row"><Icon name="sparkles" size={26} /><div><h2 className="section-title">La constance avant la complexité</h2><p className="muted">Choisis des mouvements que tu maîtrises, suis tes performances et adapte progressivement la difficulté.</p></div></div></Card><div className="grid-3">{advice.map(item => <Card key={item.title}><div className="resource-icon"><Icon name={item.icon} /></div><h3>{item.title}</h3><p>{item.text}</p><p className="muted small">{item.detail}</p></Card>)}</div><p className="muted small">Repères d’entraînement généraux pour adultes. La régularité et l’adaptation à l’objectif sont notamment soulignées par <a href="https://acsm.org/resistance-training-guidelines-update-2026/" target="_blank" rel="noreferrer">les recommandations ACSM 2026</a>. Les exemples de progression ci-dessus sont des pistes pratiques à adapter à ton expérience.</p></div>;
}

const armOptions = [
  { name: 'Curl câble', muscle: 'Biceps', difficulty: 'Accessible', benefit: 'Un réglage de charge fin et un mouvement facile à reproduire.', placement: 'En fin de PULL, comme option complémentaire à évaluer.' },
  { name: 'Curl barre EZ', muscle: 'Biceps', difficulty: 'Intermédiaire', benefit: 'Un travail bilatéral avec une prise souvent confortable.', placement: 'Après les tirages de PULL, si tu souhaites varier le travail direct.' },
  { name: 'Curl incliné', muscle: 'Biceps', difficulty: 'Intermédiaire', benefit: 'Une position du bras en arrière du buste différente du pupitre.', placement: 'En fin de PULL ; commence léger et garde l’épaule stable.' },
  { name: 'Curl pupitre', muscle: 'Biceps', difficulty: 'Accessible', benefit: 'Un appui qui aide à limiter l’élan du buste.', placement: 'Déjà présent dans ton programme initial PULL : conserve une exécution contrôlée.' },
  { name: 'Curl marteau', muscle: 'Biceps', difficulty: 'Accessible', benefit: 'La prise neutre sollicite aussi le brachial et le brachio-radial.', placement: 'Déjà prévu en version inclinée dans ton PULL initial.' },
  { name: 'Extension poulie', muscle: 'Triceps', difficulty: 'Accessible', benefit: 'Une extension du coude stable, simple à suivre et à doser.', placement: 'Après les développés de PUSH ou PUSH 2.' },
  { name: 'Extension au-dessus de la tête', muscle: 'Triceps', difficulty: 'Intermédiaire', benefit: 'Un angle de bras différent, avec la longue portion du triceps en position allongée.', placement: 'Dans PUSH 2, après les développés, si la position est confortable.' },
  { name: 'Dips assistés', muscle: 'Triceps', difficulty: 'Intermédiaire', benefit: 'Un mouvement de poussée qui fait aussi intervenir les pectoraux.', placement: 'Option dans PUSH 2 ; ajuste l’assistance et garde une amplitude confortable.' },
  { name: 'Barre au front', muscle: 'Triceps', difficulty: 'Intermédiaire', benefit: 'Une variante d’extension avec barre, réalisable sur banc.', placement: 'Après les développés de PUSH 2, avec une charge maîtrisée.' },
  { name: 'Extension unilatérale câble', muscle: 'Triceps', difficulty: 'Accessible', benefit: 'Un côté à la fois pour ajuster le trajet et contrôler l’exécution.', placement: 'En fin de PUSH 2, comme complément possible.' },
];

export function Arms() {
  const { state, navigate } = useApp();
  const [muscle, setMuscle] = useState('Tous');
  const scheduled = new Set(Object.values(state.schedule));
  const current = state.programs.filter(program => scheduled.has(program.id)).map(program => ({ ...program, arms: program.exercises.map(item => ({ ...item, exercise: state.exercises.find(exercise => exercise.id === item.exerciseId) })).filter(item => ['Biceps', 'Triceps'].includes(item.exercise?.muscle)) })).filter(program => program.arms.length);
  return <div className="page-stack"><PageHeader eyebrow="FOCUS POINT FAIBLE" title="Plus d’attention pour tes bras." description="Des pistes pour les biceps et les triceps, en gardant tes exercices de base."><Button variant="secondary" onClick={() => navigate('program')}>Personnaliser mon programme <Icon name="arrow-right" /></Button></PageHeader><Card><h2 className="section-title">Ce que ton programme prévoit déjà</h2><p className="muted">Dans ton programme initial, les curls de PULL travaillent directement les biceps. Les extensions de PUSH et PUSH 2 ciblent les triceps ; les tirages et développés sollicitent aussi les bras. Commence par suivre la progression de ces mouvements avant d’ajouter du travail.</p><div className="grid-2">{current.map(program => <div key={program.id}><Badge>{program.name}</Badge>{program.arms.map(item => <div className="list-row" key={item.exerciseId}><span className="small">{item.exercise.name}</span><strong className="small">{item.sets} × {item.repsMin}–{item.repsMax}</strong></div>)}</div>)}</div>{!current.length && <p className="muted small">Aucun exercice directement ciblé biceps ou triceps dans tes séances planifiées actuelles.</p>}<p className="small">PUSH 2 est l’occasion de porter une attention particulière aux triceps. Si tu récupères bien et que tes performances stagnent sur plusieurs semaines, évalue un complément à la fois.</p><p className="muted small">Les propositions ci-dessous ne modifient jamais ton programme automatiquement. Tu décides des ajouts depuis Programme.</p></Card><div className="chips">{['Tous', 'Biceps', 'Triceps'].map(item => <button key={item} className={`chip ${muscle === item ? 'active' : ''}`} onClick={() => setMuscle(item)}>{item}</button>)}</div><div className="grid-2">{armOptions.filter(item => muscle === 'Tous' || item.muscle === muscle).map(item => <Card key={item.name}><div className="row between"><Badge>{item.muscle}</Badge><span className="muted small">{item.difficulty}</span></div><h3>{item.name}</h3><p>{item.benefit}</p><p className="muted small"><strong>Où le placer :</strong> {item.placement}</p></Card>)}</div><p className="muted small">Les variantes changent les prises et les positions ; elles ne garantissent pas une croissance localisée ni des résultats rapides. Surveille aussi ta récupération.</p></div>;
}

const accessories = [
  { name: 'Sangles de tirage', icon: 'dumbbell', priority: 'Moyenne', price: '5–15 €', benefit: 'Peuvent aider lorsque la prise fatigue avant les muscles du dos.', exercises: 'Rowing barre, tirage horizontal, tirage vertical.', verdict: 'Utiles si la prise te limite ; facultatives autrement.', source: 'https://www.decathlon.fr/tous-les-sports/musculation-cross-training/protege-poignet' },
  { name: 'Ceinture de lest', icon: 'plus', priority: 'Faible', price: '20–45 €', benefit: 'Ajoute du lest sur des mouvements au poids du corps déjà maîtrisés.', exercises: 'Dips et tractions lestés.', verdict: 'Facultative pour ton programme actuel, surtout si tu utilises de l’assistance.', source: 'https://www.decathlon.fr/vc/ceinture-de-lestage' },
  { name: 'Bandes élastiques', icon: 'activity', priority: 'Moyenne', price: '4–26 €', benefit: 'Faciles à transporter pour s’échauffer ou s’entraîner hors de la salle.', exercises: 'Tirages légers, poussées, travail des épaules.', verdict: 'Polyvalentes ; vérifie la résistance et l’état de la bande.', source: 'https://www.decathlon.fr/tous-les-sports/musculation-cross-training/accessoires-musculation-cross-training' },
  { name: 'Wrist wraps', icon: 'shield', priority: 'Faible', price: '10–20 €', benefit: 'Apportent un maintien au poignet sur certaines poussées lourdes.', exercises: 'Développé incliné, Shoulder Press.', verdict: 'Facultatifs ; ils ne corrigent pas la technique et ne traitent pas une douleur.', source: 'https://www.decathlon.fr/p/poignet-de-serrage-musculation-force-wristwrap-gris-fonce/_/R-p-324386' },
  { name: 'Sangles de chevilles', icon: 'footprints', priority: 'Faible', price: '10–32 €', benefit: 'Permettent d’attacher la cheville à une poulie.', exercises: 'Extension de hanche, abduction à la poulie.', verdict: 'Optionnelles : tes exercices de jambes actuels n’en ont pas besoin.', source: 'https://www.decathlon.fr/p/sangle-de-tirage-musculation-avec-confort-poignet-noir/332208/c382m8642607' },
  { name: 'Ceinture de musculation', icon: 'shield', priority: 'Faible', price: '17–40 €', benefit: 'Peut servir d’appui au gainage abdominal sur des charges exigeantes.', exercises: 'Squat, rowing barre selon ta pratique.', verdict: 'Facultative. Apprends d’abord le placement et le gainage ; elle ne garantit pas contre les blessures.', source: 'https://www.decathlon.fr/tous-les-sports/musculation-cross-training/ceintures-de-musculation-ceinture-lestee' },
  { name: 'Shaker', icon: 'glass', priority: 'Moyenne', price: '6–10 €', benefit: 'Mélange ta whey et se transporte facilement.', exercises: 'Usage nutrition, indépendant de la séance.', verdict: 'Pratique si tu prends de la whey. Un récipient propre adapté peut suffire.', source: 'https://www.decathlon.fr/nutrition-sante/shakers' },
  { name: 'Boîte à compléments', icon: 'pill', priority: 'Faible', price: '4–15 €', benefit: 'Organise une portion à emporter et simplifie ta routine.', exercises: 'Usage quotidien, indépendant de la séance.', verdict: 'Facultative ; garde les produits identifiables et les consignes de conservation.', source: 'https://www.decathlon.fr/nutrition-sante/piluliers' },
  { name: 'Petite balance alimentaire', icon: 'scale', priority: 'Moyenne', price: '10–20 €', benefit: 'Aide à connaître tes portions pour renseigner les protéines.', exercises: 'Préparation des repas.', verdict: 'Utile pour prendre des repères ; un modèle simple suffit.', source: 'https://www.boulanger.com/c/balance-de-cuisine' },
];

export function Accessories() {
  const [priority, setPriority] = useState('Tous');
  return <div className="page-stack"><PageHeader eyebrow="L’ÉQUIPEMENT UTILE" title="L’essentiel dans ton sac." description="Des accessoires simples, seulement quand ils répondent à un besoin." /><Card><div className="row"><Icon name="dumbbell" size={28} /><div><h2 className="section-title">Aucun achat indispensable pour commencer</h2><p className="muted">Vérifie d’abord le matériel disponible dans ta salle. La priorité dépend de ce qui te limite réellement.</p></div></div></Card><div className="row between"><div className="chips">{['Tous', 'Moyenne', 'Faible'].map(item => <button className={`chip ${priority === item ? 'active' : ''}`} key={item} onClick={() => setPriority(item)}>{item === 'Tous' ? 'Tous les accessoires' : `Priorité ${item.toLowerCase()}`}</button>)}</div><span className="muted small">Prix indicatifs · septembre 2026</span></div><div className="grid-3">{accessories.filter(item => priority === 'Tous' || item.priority === priority).map(item => <Card key={item.name}><div className="row between"><div className="resource-icon"><Icon name={item.icon} size={25} /></div><strong className="accent">{item.price}</strong></div><h3>{item.name}</h3><Badge tone={item.priority === 'Moyenne' ? 'accent' : 'neutral'}>Priorité {item.priority.toLowerCase()}</Badge><p>{item.benefit}</p><p className="muted small"><strong>Pour :</strong> {item.exercises}</p><p className="small">{item.verdict}</p><a className="small muted" href={item.source} target="_blank" rel="noreferrer">Exemples de prix <Icon name="arrow-up-right" size={13} /></a></Card>)}</div><p className="muted small">Fourchettes de budget arrondies à partir d’exemples de distributeurs français, hors livraison. Les prix et disponibilités peuvent changer. Aucun lien affilié.</p></div>;
}
