import { today } from "./calculations.js";

export const MUSCLES = [
  "Pectoraux",
  "Dos",
  "Épaules",
  "Biceps",
  "Triceps",
  "Quadriceps",
  "Ischio-jambiers",
  "Fessiers",
  "Mollets",
  "Abdominaux",
];

const exercise = (
  id,
  name,
  muscle,
  secondary,
  movement,
  tips,
  options = {},
) => ({
  id,
  name,
  muscle,
  secondary,
  movement,
  sets: 3,
  repsMin: 8,
  repsMax: 12,
  rest: 90,
  tips,
  ...options,
});

export const DEFAULT_EXERCISES = [
  exercise(
    "incline-press",
    "Développé incliné pectoraux",
    "Pectoraux",
    ["Épaules", "Triceps"],
    "Poussée",
    [
      "Garde les omoplates stables sur le banc.",
      "Descends de façon contrôlée dans une amplitude confortable.",
    ],
    { rest: 120 },
  ),
  exercise(
    "shoulder-press",
    "Shoulder Press",
    "Épaules",
    ["Triceps"],
    "Poussée",
    [
      "Garde le tronc stable et les poignets alignés.",
      "Ne compense pas en cambrant excessivement le dos.",
    ],
    { rest: 120 },
  ),
  exercise(
    "triceps-extension",
    "Extension triceps",
    "Triceps",
    [],
    "Extension",
    [
      "Garde les coudes proches du corps.",
      "Contrôle le retour sans laisser la charge te tirer.",
    ],
  ),
  exercise(
    "high-cable-fly",
    "Tirage poulie haute pectoraux",
    "Pectoraux",
    ["Épaules"],
    "Adduction",
    [
      "Garde une légère flexion des coudes.",
      "Rapproche les mains avec les pectoraux, sans élan.",
    ],
    { repsMin: 10, repsMax: 15 },
  ),
  exercise(
    "lateral-raise",
    "Élévations latérales",
    "Épaules",
    [],
    "Élévation",
    [
      "Monte les bras sans hausser les épaules.",
      "Utilise une charge qui permet de contrôler la descente.",
    ],
    { repsMin: 12, repsMax: 20, rest: 60 },
  ),
  exercise(
    "lat-pulldown",
    "Tirage vertical dos",
    "Dos",
    ["Biceps"],
    "Tirage vertical",
    [
      "Amène les coudes vers le bas.",
      "Garde le buste stable et évite de tirer derrière la nuque.",
    ],
    { rest: 120 },
  ),
  exercise("preacher-curl", "Curl pupitre", "Biceps", [], "Flexion", [
    "Garde le bras en contact avec le pupitre.",
    "Évite de verrouiller brutalement le coude en bas.",
  ]),
  exercise(
    "seated-row",
    "Tirage horizontal",
    "Dos",
    ["Biceps"],
    "Tirage horizontal",
    [
      "Tire les coudes vers l’arrière sans donner d’élan.",
      "Laisse les omoplates bouger naturellement.",
    ],
    { rest: 120 },
  ),
  exercise(
    "incline-hammer-curl",
    "Curl marteau incliné sur banc",
    "Biceps",
    [],
    "Flexion",
    [
      "Garde les paumes face à face.",
      "Laisse les bras près du buste et contrôle la descente.",
    ],
  ),
  exercise(
    "barbell-row",
    "Rowing barre",
    "Dos",
    ["Biceps", "Ischio-jambiers"],
    "Tirage horizontal",
    [
      "Garde le tronc stable et les hanches reculées.",
      "Ramène la barre sans redresser le buste à chaque répétition.",
    ],
    { rest: 120 },
  ),
  exercise(
    "half-squat",
    "Half Squat",
    "Quadriceps",
    ["Fessiers"],
    "Squat",
    [
      "Conserve une amplitude reproductible et confortable.",
      "Garde les pieds stables et les genoux dans leur axe.",
    ],
    { rest: 180 },
  ),
  exercise(
    "leg-extension",
    "Leg Extension",
    "Quadriceps",
    [],
    "Extension",
    [
      "Aligne le genou avec l’axe de la machine.",
      "Évite de projeter la charge.",
    ],
    { repsMin: 10, repsMax: 15 },
  ),
  exercise(
    "leg-curl",
    "Leg Curl",
    "Ischio-jambiers",
    [],
    "Flexion",
    [
      "Règle la machine à ta morphologie.",
      "Garde le bassin stable pendant le mouvement.",
    ],
    { repsMin: 10, repsMax: 15 },
  ),
  exercise(
    "leg-press",
    "Leg Press",
    "Quadriceps",
    ["Fessiers"],
    "Poussée",
    [
      "Garde le bassin et le dos en contact avec le dossier.",
      "Descends dans une amplitude contrôlée sans décoller le bassin.",
    ],
    { rest: 180 },
  ),
  exercise(
    "flat-dumbbell-press",
    "Développé couché haltères",
    "Pectoraux",
    ["Épaules", "Triceps"],
    "Poussée",
    [
      "Stabilise les épaules sur le banc.",
      "Garde les poignets au-dessus des coudes.",
    ],
    { rest: 120 },
  ),
  exercise(
    "overhead-triceps-extension",
    "Extension triceps au-dessus de la tête",
    "Triceps",
    [],
    "Extension",
    [
      "Garde le tronc stable.",
      "Choisis une amplitude confortable pour les épaules et les coudes.",
    ],
    { repsMin: 10, repsMax: 15 },
  ),
  exercise("cable-curl", "Curl câble", "Biceps", [], "Flexion", [
    "Garde les coudes stables.",
    "Contrôle la charge sur toute la répétition.",
  ]),
  exercise("ez-curl", "Curl barre EZ", "Biceps", [], "Flexion", [
    "Choisis une prise confortable pour les poignets.",
    "Évite le balancement du buste.",
  ]),
  exercise("incline-curl", "Curl incliné", "Biceps", [], "Flexion", [
    "Garde les épaules contre le dossier.",
    "Ne laisse pas les coudes partir vers l’avant.",
  ]),
  exercise("hammer-curl", "Curl marteau", "Biceps", [], "Flexion", [
    "Garde une prise neutre.",
    "Évite de donner de l’élan avec les hanches.",
  ]),
  exercise(
    "concentration-curl",
    "Curl concentration",
    "Biceps",
    [],
    "Flexion",
    [
      "Appuie le bras contre la cuisse.",
      "Effectue le mouvement lentement, sans tourner le buste.",
    ],
  ),
  exercise(
    "assisted-dips",
    "Dips assistés",
    "Triceps",
    ["Pectoraux", "Épaules"],
    "Poussée",
    [
      "Règle l’assistance pour garder le contrôle.",
      "Arrête la descente avant toute gêne à l’épaule.",
    ],
    { rest: 120 },
  ),
  exercise("skull-crusher", "Barre au front", "Triceps", [], "Extension", [
    "Garde les bras stables.",
    "Descends lentement et choisis une charge maîtrisée.",
  ]),
  exercise(
    "single-arm-triceps",
    "Extension unilatérale câble",
    "Triceps",
    [],
    "Extension",
    [
      "Garde le coude stable près du buste.",
      "Effectue le même nombre de répétitions de chaque côté.",
    ],
  ),
  exercise(
    "rope-pushdown",
    "Extension poulie corde",
    "Triceps",
    [],
    "Extension",
    [
      "Garde les épaules basses et les coudes stables.",
      "Écarte légèrement les mains en fin d’extension si cela reste confortable.",
    ],
  ),
  exercise("pec-deck", "Pec deck", "Pectoraux", [], "Adduction", [
    "Règle la hauteur du siège avant de commencer.",
    "Garde le dos appuyé et évite de tirer les épaules trop en arrière.",
  ]),
  exercise(
    "push-ups",
    "Pompes",
    "Pectoraux",
    ["Triceps", "Épaules", "Abdominaux"],
    "Poussée",
    [
      "Garde le corps aligné.",
      "Adapte la hauteur des mains si les répétitions deviennent difficiles.",
    ],
  ),
  exercise(
    "pull-up",
    "Tractions",
    "Dos",
    ["Biceps"],
    "Tirage vertical",
    [
      "Démarre chaque répétition sans balancement.",
      "Utilise une assistance si nécessaire pour contrôler le mouvement.",
    ],
    { rest: 120 },
  ),
  exercise(
    "one-arm-row",
    "Rowing haltère unilatéral",
    "Dos",
    ["Biceps"],
    "Tirage horizontal",
    [
      "Prends un appui stable.",
      "Tire le coude vers la hanche sans tourner le buste.",
    ],
    { rest: 120 },
  ),
  exercise(
    "straight-arm-pulldown",
    "Pull-over à la poulie",
    "Dos",
    [],
    "Extension d’épaule",
    [
      "Garde les coudes légèrement fléchis.",
      "Évite de cambrer pour terminer le mouvement.",
    ],
  ),
  exercise(
    "rear-delt-fly",
    "Oiseau haltères",
    "Épaules",
    ["Dos"],
    "Élévation",
    ["Garde le buste stable.", "Écarte les bras sans hausser les épaules."],
    { repsMin: 12, repsMax: 20, rest: 60 },
  ),
  exercise(
    "face-pull",
    "Face pull",
    "Épaules",
    ["Dos"],
    "Tirage horizontal",
    [
      "Tire la corde vers le visage avec contrôle.",
      "Garde les épaules dans une position confortable.",
    ],
    { repsMin: 12, repsMax: 20 },
  ),
  exercise(
    "goblet-squat",
    "Goblet squat",
    "Quadriceps",
    ["Fessiers", "Abdominaux"],
    "Squat",
    [
      "Garde la charge près de la poitrine.",
      "Choisis une profondeur compatible avec une posture stable.",
    ],
    { rest: 120 },
  ),
  exercise(
    "bulgarian-squat",
    "Fente bulgare",
    "Quadriceps",
    ["Fessiers"],
    "Fente",
    [
      "Trouve d’abord une position stable sans charge.",
      "Descends verticalement avec contrôle.",
    ],
    { rest: 120 },
  ),
  exercise(
    "walking-lunge",
    "Fentes marchées",
    "Quadriceps",
    ["Fessiers"],
    "Fente",
    [
      "Garde une largeur de pas suffisante pour l’équilibre.",
      "Contrôle chaque appui avant la répétition suivante.",
    ],
    { rest: 120 },
  ),
  exercise(
    "romanian-deadlift",
    "Soulevé de terre roumain",
    "Ischio-jambiers",
    ["Fessiers", "Dos"],
    "Charnière de hanche",
    [
      "Recule les hanches en gardant la charge près des jambes.",
      "Arrête la descente avant de perdre la position du dos.",
    ],
    { rest: 180 },
  ),
  exercise(
    "seated-leg-curl",
    "Leg Curl assis",
    "Ischio-jambiers",
    [],
    "Flexion",
    [
      "Règle le coussin pour maintenir les cuisses.",
      "Contrôle le retour jusqu’à la position de départ.",
    ],
    { repsMin: 10, repsMax: 15 },
  ),
  exercise(
    "hip-thrust",
    "Hip thrust",
    "Fessiers",
    ["Ischio-jambiers"],
    "Extension de hanche",
    [
      "Garde les côtes abaissées.",
      "Termine avec les hanches sans cambrer excessivement.",
    ],
    { rest: 120 },
  ),
  exercise(
    "cable-kickback",
    "Extension de hanche à la poulie",
    "Fessiers",
    ["Ischio-jambiers"],
    "Extension de hanche",
    [
      "Garde le bassin face à la machine.",
      "Utilise une amplitude contrôlée, sans élan.",
    ],
    { repsMin: 12, repsMax: 20 },
  ),
  exercise(
    "hip-abduction",
    "Abduction de hanche",
    "Fessiers",
    [],
    "Abduction",
    [
      "Garde le bassin stable.",
      "Ouvre les jambes sans rebondir sur la charge.",
    ],
    { repsMin: 12, repsMax: 20 },
  ),
  exercise(
    "standing-calf",
    "Mollets debout",
    "Mollets",
    [],
    "Flexion plantaire",
    [
      "Utilise une amplitude confortable et régulière.",
      "Marque une courte pause sans rebondir.",
    ],
    { repsMin: 12, repsMax: 20, rest: 60 },
  ),
  exercise(
    "seated-calf",
    "Mollets assis",
    "Mollets",
    [],
    "Flexion plantaire",
    ["Garde l’avant-pied bien posé.", "Contrôle le bas du mouvement."],
    { repsMin: 12, repsMax: 20, rest: 60 },
  ),
  exercise(
    "cable-crunch",
    "Crunch à la poulie",
    "Abdominaux",
    [],
    "Flexion du tronc",
    [
      "Enroule le tronc sans tirer uniquement avec les bras.",
      "Expire pendant la contraction.",
    ],
    { repsMin: 12, repsMax: 20, rest: 60 },
  ),
  exercise(
    "reverse-crunch",
    "Crunch inversé",
    "Abdominaux",
    [],
    "Flexion du tronc",
    [
      "Décolle légèrement le bassin avec contrôle.",
      "Évite de balancer les jambes.",
    ],
    { repsMin: 12, repsMax: 20, rest: 60 },
  ),
  exercise(
    "hanging-knee-raise",
    "Relevé de genoux",
    "Abdominaux",
    [],
    "Flexion de hanche",
    ["Évite le balancement.", "Ramène le bassin légèrement vers le haut."],
    { repsMin: 10, repsMax: 15, rest: 60 },
  ),
];

function programEntry(id, overrides = {}) {
  const item = DEFAULT_EXERCISES.find((entry) => entry.id === id);
  return {
    exerciseId: id,
    sets: item.sets,
    repsMin: item.repsMin,
    repsMax: item.repsMax,
    rest: item.rest,
    ...overrides,
  };
}

export const DEFAULT_PROGRAMS = [
  {
    id: "push",
    name: "PUSH",
    description: "Pectoraux, épaules & triceps",
    color: "#c4ed83",
    exercises: [
      "incline-press",
      "shoulder-press",
      "triceps-extension",
      "high-cable-fly",
      "lateral-raise",
    ].map((id) => programEntry(id)),
  },
  {
    id: "pull",
    name: "PULL",
    description: "Dos & biceps",
    color: "#9eb9e2",
    exercises: [
      "lat-pulldown",
      "preacher-curl",
      "seated-row",
      "incline-hammer-curl",
      "barbell-row",
    ].map((id) => programEntry(id)),
  },
  {
    id: "legs",
    name: "LEGS",
    description: "Quadriceps, ischios & fessiers",
    color: "#d5b8e8",
    exercises: ["half-squat", "leg-extension", "leg-curl", "leg-press"].map(
      (id) => programEntry(id),
    ),
  },
  {
    id: "push2",
    name: "PUSH 2",
    description: "Pectoraux, épaules & priorité triceps",
    color: "#e7c09b",
    exercises: [
      "flat-dumbbell-press",
      "shoulder-press",
      "overhead-triceps-extension",
      "single-arm-triceps",
      "lateral-raise",
    ].map((id) => programEntry(id)),
  },
];

export function createInitialState() {
  return {
    schemaVersion: 2,
    onboardingComplete: false,
    profile: {
      firstName: "",
      age: 25,
      height: 175,
      sex: "unspecified",
      weight: 72,
      targetWeight: 76,
      goal: "gain",
      frequency: 4,
      proteinTarget: 130,
      proteinMode: "estimate",
      trackProtein: true,
      trackWhey: true,
      trackCreatine: true,
      creatineDose: 3,
      wheyProtein: 25,
      waterGoal: 2500,
      sleepGoal: 8,
      streakMode: "training",
      unit: "kg",
      theme: "dark",
      startDate: today(),
      targetDate: "",
      restSeconds: 90,
      autoTimer: true,
    },
    exercises: structuredClone(DEFAULT_EXERCISES),
    programs: structuredClone(DEFAULT_PROGRAMS),
    schedule: { 1: "push", 3: "pull", 5: "legs", 6: "push2" },
    scheduleTime: "18:00",
    exceptions: {},
    sessions: [],
    weights: [],
    meals: [],
    supplements: {},
    hydration: [],
    sleep: [],
    rankHistory: [],
    goals: [],
    reminders: {
      creatine: {
        enabled: false,
        time: "18:00",
        days: [0, 1, 2, 3, 4, 5, 6],
        type: "inapp",
      },
      whey: {
        enabled: false,
        time: "19:00",
        days: [0, 1, 2, 3, 4, 5, 6],
        type: "inapp",
        afterTraining: false,
      },
      training: {
        enabled: false,
        time: "18:00",
        days: [1, 3, 5, 6],
        type: "inapp",
      },
      water: {
        enabled: false,
        time: "16:00",
        days: [0, 1, 2, 3, 4, 5, 6],
        type: "inapp",
      },
    },
    draft: null,
  };
}
