import React, {useState} from 'react';
import {useApp} from './context';
import {Brand,Button,Field,Icon} from './components';
import {estimateProtein,today} from './calculations';
export default function Onboarding(){const {state,update,notify}=useApp();const [step,setStep]=useState(0),[form,setForm]=useState({...state.profile,weight:'',targetWeight:''});const set=(key,value)=>setForm(f=>({...f,[key]:value}));
 function finish(e){e.preventDefault();const profile={...form,weight:Number(form.weight),targetWeight:Number(form.targetWeight)||Number(form.weight),height:Number(form.height),age:Number(form.age),frequency:Number(form.frequency),proteinTarget:estimateProtein(Number(form.weight),form.goal,Number(form.frequency)),startDate:today()};update(s=>({...s,profile,onboardingComplete:true,weights:[{id:crypto.randomUUID(),date:today(),weight:profile.weight,note:'Mon point de départ'}]}));notify('Votre espace est prêt. À vous de jouer !');}
 return <div className="onboarding-backdrop"><div className="onboarding" role="dialog" aria-modal="true" aria-labelledby="welcome-title"><Brand/><div className="onboarding-steps">{[0,1,2].map(i=><span key={i} className={i<=step?'active':''}/>)}</div><div className="eyebrow">VOTRE POINT DE DÉPART · {step+1}/3</div><h1 id="welcome-title">{['Un peu de vous.','Un objectif, votre rythme.','Prêt à progresser ?'][step]}</h1><p className="muted">{['Quelques repères pour un suivi qui vous ressemble.','Votre programme est déjà prêt. Vous gardez la main.','Choisissez ce que vous souhaitez suivre au quotidien.'][step]}</p><form onSubmit={step===2?finish:e=>{e.preventDefault();setStep(step+1);}} className="page-stack">
 {step===0&&<><Field label="Votre prénom"><input autoFocus placeholder="Comment vous appeler ?" maxLength="40" value={form.firstName} onChange={e=>set('firstName',e.target.value)}/></Field><div className="form-grid"><Field label="Poids actuel (kg)"><input required type="number" inputMode="decimal" min="25" max="400" step="0.1" placeholder="72,0" value={form.weight} onChange={e=>set('weight',e.target.value)}/></Field><Field label="Taille (cm)"><input required type="number" min="100" max="250" value={form.height} onChange={e=>set('height',Number(e.target.value))}/></Field><Field label="Âge"><input required type="number" min="16" max="100" value={form.age} onChange={e=>set('age',Number(e.target.value))}/></Field><Field label="Sexe (facultatif)"><select value={form.sex} onChange={e=>set('sex',e.target.value)}><option value="unspecified">Non renseigné</option><option value="male">Homme</option><option value="female">Femme</option></select></Field></div></>}
 {step===1&&<><Field label="Votre objectif sportif"><select value={form.goal} onChange={e=>set('goal',e.target.value)}><option value="gain">Prise de masse</option><option value="maintain">Maintien</option><option value="lose">Perte de poids</option></select></Field><div className="form-grid"><Field label="Poids cible (kg)"><input required type="number" inputMode="decimal" min="25" max="400" step="0.1" placeholder={String(form.weight)} value={form.targetWeight} onChange={e=>set('targetWeight',e.target.value)}/></Field><Field label="Séances souhaitées / semaine"><select value={form.frequency} onChange={e=>set('frequency',Number(e.target.value))}>{[1,2,3,4,5,6,7].map(n=><option key={n} value={n}>{n} séances</option>)}</select></Field></div><div className="info-box"><Icon name="calendar"/><div><strong>Votre programme de base</strong><p>Lundi PUSH · Mercredi PULL · Vendredi LEGS · Samedi PUSH 2</p><span className="small muted">4 séances conservées par défaut. Modifiez les jours dans Programme selon votre rythme.</span></div></div></>}
 {step===2&&<><div className="onboarding-estimate"><Icon name="utensils" size={25}/><span>Votre repère protéines<strong>{estimateProtein(Number(form.weight),form.goal,form.frequency)} <small>g / jour</small></strong></span></div><p className="small muted">Estimation générale, modifiable dans Nutrition. Elle ne constitue pas une prescription médicale. Pour un mineur, faites valider cet objectif par un professionnel.</p>{[['trackProtein','Protéines','Repas et objectif quotidien'],['trackWhey','Whey','Un suivi informatif, selon vos besoins'],['trackCreatine','Créatine','Une quantité choisie par vous']].map(([key,label,desc])=><label className="toggle-row" key={key}><span><strong>{label}</strong><small>{desc}</small></span><input className="switch" type="checkbox" checked={form[key]} onChange={e=>set(key,e.target.checked)}/></label>)}<div className="privacy-note"><Icon name="shield" size={17}/>Vos données sont enregistrées sur cet appareil et synchronisées avec votre compte.</div></>}
 <div className="row between">{step>0?<Button variant="ghost" onClick={()=>setStep(step-1)}><Icon name="arrow-left"/>Retour</Button>:<Button variant="ghost" onClick={()=>update(s=>({...s,onboardingComplete:true}))}>Configurer plus tard</Button>}<Button type="submit">{step===2?'Créer mon espace':'Continuer'}<Icon name="arrow-right" size={17}/></Button></div></form></div></div>;
}
